/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitRouteImport } from './routes/visit'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as ApiPublicRazorpayVerifyRouteImport } from './routes/api/public/razorpay/verify'
import { Route as ApiPublicRazorpayCreateOrderRouteImport } from './routes/api/public/razorpay/create-order'

const VisitRoute = VisitRouteImport.update({
  id: '/visit',
  path: '/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayVerifyRoute = ApiPublicRazorpayVerifyRouteImport.update({
  id: '/api/public/razorpay/verify',
  path: '/api/public/razorpay/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayCreateOrderRoute =
  ApiPublicRazorpayCreateOrderRouteImport.update({
    id: '/api/public/razorpay/create-order',
    path: '/api/public/razorpay/create-order',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/order-success': typeof OrderSuccessRoute
  '/visit': typeof VisitRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/api/public/razorpay/create-order': typeof ApiPublicRazorpayCreateOrderRoute
  '/api/public/razorpay/verify': typeof ApiPublicRazorpayVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/order-success': typeof OrderSuccessRoute
  '/visit': typeof VisitRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal': typeof JournalIndexRoute
  '/api/public/razorpay/create-order': typeof ApiPublicRazorpayCreateOrderRoute
  '/api/public/razorpay/verify': typeof ApiPublicRazorpayVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/order-success': typeof OrderSuccessRoute
  '/visit': typeof VisitRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/journal/': typeof JournalIndexRoute
  '/api/public/razorpay/create-order': typeof ApiPublicRazorpayCreateOrderRoute
  '/api/public/razorpay/verify': typeof ApiPublicRazorpayVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/catalog'
    | '/order-success'
    | '/visit'
    | '/journal/$slug'
    | '/journal/'
    | '/api/public/razorpay/create-order'
    | '/api/public/razorpay/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/catalog'
    | '/order-success'
    | '/visit'
    | '/journal/$slug'
    | '/journal'
    | '/api/public/razorpay/create-order'
    | '/api/public/razorpay/verify'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/catalog'
    | '/order-success'
    | '/visit'
    | '/journal/$slug'
    | '/journal/'
    | '/api/public/razorpay/create-order'
    | '/api/public/razorpay/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  VisitRoute: typeof VisitRoute
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
  ApiPublicRazorpayCreateOrderRoute: typeof ApiPublicRazorpayCreateOrderRoute
  ApiPublicRazorpayVerifyRoute: typeof ApiPublicRazorpayVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visit': {
      id: '/visit'
      path: '/visit'
      fullPath: '/visit'
      preLoaderRoute: typeof VisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay/verify': {
      id: '/api/public/razorpay/verify'
      path: '/api/public/razorpay/verify'
      fullPath: '/api/public/razorpay/verify'
      preLoaderRoute: typeof ApiPublicRazorpayVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay/create-order': {
      id: '/api/public/razorpay/create-order'
      path: '/api/public/razorpay/create-order'
      fullPath: '/api/public/razorpay/create-order'
      preLoaderRoute: typeof ApiPublicRazorpayCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  VisitRoute: VisitRoute,
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
  ApiPublicRazorpayCreateOrderRoute: ApiPublicRazorpayCreateOrderRoute,
  ApiPublicRazorpayVerifyRoute: ApiPublicRazorpayVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
